/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface Treasure extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Treasure;
  clone(): Treasure;
  methods: {
    treasuresReceived(
      arg0: string | number[]
    ): NonPayableTransactionObject<string>;

    treasureList(
      arg0: number | string | BN
    ): NonPayableTransactionObject<string>;

    totalTreasuresFor(
      treasure: string | number[]
    ): NonPayableTransactionObject<string>;

    claimForTreasure(
      treasure: string | number[]
    ): NonPayableTransactionObject<void>;

    validTreasure(
      treasure: string | number[]
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
